name: Deploy API

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

<<<<<<< HEAD
      - name: Check for Outdated Dependencies
        run: npm outdated

      - name: Set Directory Permissions
        run: chmod -R 777 .

      - name: Run Tests
        run: npx jest --runInBand
=======
      # - name: Run Tests
      #   run: npm install --save-dev jest  # Use npx to avoid permission issues
>>>>>>> ca674b675587a20d5a2b3537bafacdc1e888bfbe

      - name: Build Docker Image
        run: docker build -t networth-tracker-api .