name: Deploy API

on: push

jobs:
  build:
    runs-on: ubuntu-latest  # This runs on a Linux VM in GitHub Actions, so Windows setup isn't needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm install --save-dev jest  # Use npx to avoid permission issues

      - name: Build Docker Image
        run: docker build -t networth-tracker-api .
